# Generated by Django 4.0.1 on 2022-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=80, verbose_name='Surname'),
        ),
    ]
