# Generated by Django 4.0.1 on 2022-01-14 18:39

import django.contrib.postgres.fields.citext
import django.core.validators
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Last Name')),
                ('surname', models.CharField(blank=True, max_length=80, verbose_name='Surname')),
                ('email', django.contrib.postgres.fields.citext.CICharField(max_length=80, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
