# Generated by Django 4.0.1 on 2022-01-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('fr', 'French'), ('de', 'German')], max_length=7, verbose_name='Language')),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, verbose_name='Publication Year')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
