# Generated by Django 4.0.1 on 2022-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveSmallIntegerField(verbose_name='Publication Year'),
        ),
    ]
